Data <- read.table("household_power_consumption.txt",skip=66600,nrow=3000,header=TRUE,sep=";")
Data <- Data[Data[,1]=="1/2/2007" | Data[,1]=="2/2/2007",]
x <- paste(Data[,1],Data[,2])
Data[,1] <- as.Date(Data[,1],"%d/%m/%Y")
Data$Time <- strptime(x,format="%d/%m/%Y %H:%M:%S")
par(mfrow=c(2,2))
with(Data, {
  plot(Time,Data[,3],ylab="Global Active Power",xlab="",type='l')
  plot(Time,Data[,5],ylab="Voltage",xlab="datetime",type='l')
  plot(Time,Data[,7],type='l',ylab="Energy sub metering",xlab="")
  lines(Time,Data[,8],col='orangered')
  lines(Time,Data[,9],col='blue')
  legend("topright",lty=1,box.lwd=1,col=c(1,"orangered","blue"),cex=0.25,legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(Time,Data[,4],ylab="Global_reactive_power",xlab="datetime",type='l')
})
